# Starter pipeline
- task: AzureCLI@2
  inputs:
    azureSubscription: 'Azure for Students(3457d5d0-1535-40c6-85fb-cb1919104698)'
    scriptType: 'ps'
    scriptLocation: 'inlineScript'
    inlineScript: 'az login'
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- task: DownloadPipelineArtifact@2
  inputs:
    buildType: 'current'
    targetPath: '$(Pipeline.Workspace)'
- main

pool:
  vmImage: ubuntu-latest

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'
